apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-cluster
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: mshubham042/nodetest:v1
        ports: 
        - containerPort: 3000
